title: Package Stats
author: Max Grover
copyright: '2022'
execute:
  execute_notebooks: "off"
parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - linkify
    - substitution
    - tasklist
  myst_url_schemes:
    - mailto
    - http
    - https
  myst_dmath_double_inline: true
